// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家输入类型
type InputType int32

const (
	InputType_INPUT_NONE       InputType = 0
	InputType_INPUT_MOVE_UP    InputType = 1
	InputType_INPUT_MOVE_DOWN  InputType = 2
	InputType_INPUT_MOVE_LEFT  InputType = 3
	InputType_INPUT_MOVE_RIGHT InputType = 4
	InputType_INPUT_SHOOT      InputType = 5
)

// Enum value maps for InputType.
var (
	InputType_name = map[int32]string{
		0: "INPUT_NONE",
		1: "INPUT_MOVE_UP",
		2: "INPUT_MOVE_DOWN",
		3: "INPUT_MOVE_LEFT",
		4: "INPUT_MOVE_RIGHT",
		5: "INPUT_SHOOT",
	}
	InputType_value = map[string]int32{
		"INPUT_NONE":       0,
		"INPUT_MOVE_UP":    1,
		"INPUT_MOVE_DOWN":  2,
		"INPUT_MOVE_LEFT":  3,
		"INPUT_MOVE_RIGHT": 4,
		"INPUT_SHOOT":      5,
	}
)

func (x InputType) Enum() *InputType {
	p := new(InputType)
	*p = x
	return p
}

func (x InputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InputType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_proto_enumTypes[0].Descriptor()
}

func (InputType) Type() protoreflect.EnumType {
	return &file_proto_game_proto_enumTypes[0]
}

func (x InputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InputType.Descriptor instead.
func (InputType) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

// 连接成功，分配给客户端的 player_id
type ConnectSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YourPlayerId  string                 `protobuf:"bytes,1,opt,name=your_player_id,json=yourPlayerId,proto3" json:"your_player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectSuccess) Reset() {
	*x = ConnectSuccess{}
	mi := &file_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectSuccess) ProtoMessage() {}

func (x *ConnectSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectSuccess.ProtoReflect.Descriptor instead.
func (*ConnectSuccess) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectSuccess) GetYourPlayerId() string {
	if x != nil {
		return x.YourPlayerId
	}
	return ""
}

// 玩家输入
type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	InputType     InputType              `protobuf:"varint,2,opt,name=input_type,json=inputType,proto3,enum=tankgame.InputType" json:"input_type,omitempty"`
	FrameNumber   int64                  `protobuf:"varint,3,opt,name=frame_number,json=frameNumber,proto3" json:"frame_number,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInput) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerInput) GetInputType() InputType {
	if x != nil {
		return x.InputType
	}
	return InputType_INPUT_NONE
}

func (x *PlayerInput) GetFrameNumber() int64 {
	if x != nil {
		return x.FrameNumber
	}
	return 0
}

func (x *PlayerInput) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 帧输入转发
type FrameInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameNumber   int64                  `protobuf:"varint,1,opt,name=frame_number,json=frameNumber,proto3" json:"frame_number,omitempty"`
	Inputs        []*PlayerInput         `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameInputs) Reset() {
	*x = FrameInputs{}
	mi := &file_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameInputs) ProtoMessage() {}

func (x *FrameInputs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameInputs.ProtoReflect.Descriptor instead.
func (*FrameInputs) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *FrameInputs) GetFrameNumber() int64 {
	if x != nil {
		return x.FrameNumber
	}
	return 0
}

func (x *FrameInputs) GetInputs() []*PlayerInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// 房间信息
type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerIds     []string               `protobuf:"bytes,2,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "waiting", "playing", "ended"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *RoomInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 游戏开始
type GameStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerIds     []string               `protobuf:"bytes,2,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	RandomSeed    int64                  `protobuf:"varint,3,opt,name=random_seed,json=randomSeed,proto3" json:"random_seed,omitempty"` // 新增
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStart) Reset() {
	*x = GameStart{}
	mi := &file_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStart) ProtoMessage() {}

func (x *GameStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStart.ProtoReflect.Descriptor instead.
func (*GameStart) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameStart) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameStart) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *GameStart) GetRandomSeed() int64 {
	if x != nil {
		return x.RandomSeed
	}
	return 0
}

// 服务器消息
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ServerMessage_FrameInputs
	//	*ServerMessage_RoomInfo
	//	*ServerMessage_GameStart
	//	*ServerMessage_ConnectSuccess
	Data          isServerMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *ServerMessage) GetData() isServerMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ServerMessage) GetFrameInputs() *FrameInputs {
	if x != nil {
		if x, ok := x.Data.(*ServerMessage_FrameInputs); ok {
			return x.FrameInputs
		}
	}
	return nil
}

func (x *ServerMessage) GetRoomInfo() *RoomInfo {
	if x != nil {
		if x, ok := x.Data.(*ServerMessage_RoomInfo); ok {
			return x.RoomInfo
		}
	}
	return nil
}

func (x *ServerMessage) GetGameStart() *GameStart {
	if x != nil {
		if x, ok := x.Data.(*ServerMessage_GameStart); ok {
			return x.GameStart
		}
	}
	return nil
}

func (x *ServerMessage) GetConnectSuccess() *ConnectSuccess {
	if x != nil {
		if x, ok := x.Data.(*ServerMessage_ConnectSuccess); ok {
			return x.ConnectSuccess
		}
	}
	return nil
}

type isServerMessage_Data interface {
	isServerMessage_Data()
}

type ServerMessage_FrameInputs struct {
	FrameInputs *FrameInputs `protobuf:"bytes,1,opt,name=frame_inputs,json=frameInputs,proto3,oneof"`
}

type ServerMessage_RoomInfo struct {
	RoomInfo *RoomInfo `protobuf:"bytes,2,opt,name=room_info,json=roomInfo,proto3,oneof"`
}

type ServerMessage_GameStart struct {
	GameStart *GameStart `protobuf:"bytes,3,opt,name=game_start,json=gameStart,proto3,oneof"`
}

type ServerMessage_ConnectSuccess struct {
	ConnectSuccess *ConnectSuccess `protobuf:"bytes,4,opt,name=connect_success,json=connectSuccess,proto3,oneof"`
}

func (*ServerMessage_FrameInputs) isServerMessage_Data() {}

func (*ServerMessage_RoomInfo) isServerMessage_Data() {}

func (*ServerMessage_GameStart) isServerMessage_Data() {}

func (*ServerMessage_ConnectSuccess) isServerMessage_Data() {}

// 客户端消息
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ClientMessage_PlayerInput
	Data          isClientMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_proto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *ClientMessage) GetData() isClientMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClientMessage) GetPlayerInput() *PlayerInput {
	if x != nil {
		if x, ok := x.Data.(*ClientMessage_PlayerInput); ok {
			return x.PlayerInput
		}
	}
	return nil
}

type isClientMessage_Data interface {
	isClientMessage_Data()
}

type ClientMessage_PlayerInput struct {
	PlayerInput *PlayerInput `protobuf:"bytes,1,opt,name=player_input,json=playerInput,proto3,oneof"`
}

func (*ClientMessage_PlayerInput) isClientMessage_Data() {}

var File_proto_game_proto protoreflect.FileDescriptor

const file_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x10proto/game.proto\x12\btankgame\"6\n" +
	"\x0eConnectSuccess\x12$\n" +
	"\x0eyour_player_id\x18\x01 \x01(\tR\fyourPlayerId\"\x9f\x01\n" +
	"\vPlayerInput\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x122\n" +
	"\n" +
	"input_type\x18\x02 \x01(\x0e2\x13.tankgame.InputTypeR\tinputType\x12!\n" +
	"\fframe_number\x18\x03 \x01(\x03R\vframeNumber\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"_\n" +
	"\vFrameInputs\x12!\n" +
	"\fframe_number\x18\x01 \x01(\x03R\vframeNumber\x12-\n" +
	"\x06inputs\x18\x02 \x03(\v2\x15.tankgame.PlayerInputR\x06inputs\"Z\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\tR\tplayerIds\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"d\n" +
	"\tGameStart\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\tR\tplayerIds\x12\x1f\n" +
	"\vrandom_seed\x18\x03 \x01(\x03R\n" +
	"randomSeed\"\x81\x02\n" +
	"\rServerMessage\x12:\n" +
	"\fframe_inputs\x18\x01 \x01(\v2\x15.tankgame.FrameInputsH\x00R\vframeInputs\x121\n" +
	"\troom_info\x18\x02 \x01(\v2\x12.tankgame.RoomInfoH\x00R\broomInfo\x124\n" +
	"\n" +
	"game_start\x18\x03 \x01(\v2\x13.tankgame.GameStartH\x00R\tgameStart\x12C\n" +
	"\x0fconnect_success\x18\x04 \x01(\v2\x18.tankgame.ConnectSuccessH\x00R\x0econnectSuccessB\x06\n" +
	"\x04data\"S\n" +
	"\rClientMessage\x12:\n" +
	"\fplayer_input\x18\x01 \x01(\v2\x15.tankgame.PlayerInputH\x00R\vplayerInputB\x06\n" +
	"\x04data*\x7f\n" +
	"\tInputType\x12\x0e\n" +
	"\n" +
	"INPUT_NONE\x10\x00\x12\x11\n" +
	"\rINPUT_MOVE_UP\x10\x01\x12\x13\n" +
	"\x0fINPUT_MOVE_DOWN\x10\x02\x12\x13\n" +
	"\x0fINPUT_MOVE_LEFT\x10\x03\x12\x14\n" +
	"\x10INPUT_MOVE_RIGHT\x10\x04\x12\x0f\n" +
	"\vINPUT_SHOOT\x10\x05B\x0eZ\fserver/protob\x06proto3"

var (
	file_proto_game_proto_rawDescOnce sync.Once
	file_proto_game_proto_rawDescData []byte
)

func file_proto_game_proto_rawDescGZIP() []byte {
	file_proto_game_proto_rawDescOnce.Do(func() {
		file_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)))
	})
	return file_proto_game_proto_rawDescData
}

var file_proto_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_game_proto_goTypes = []any{
	(InputType)(0),         // 0: tankgame.InputType
	(*ConnectSuccess)(nil), // 1: tankgame.ConnectSuccess
	(*PlayerInput)(nil),    // 2: tankgame.PlayerInput
	(*FrameInputs)(nil),    // 3: tankgame.FrameInputs
	(*RoomInfo)(nil),       // 4: tankgame.RoomInfo
	(*GameStart)(nil),      // 5: tankgame.GameStart
	(*ServerMessage)(nil),  // 6: tankgame.ServerMessage
	(*ClientMessage)(nil),  // 7: tankgame.ClientMessage
}
var file_proto_game_proto_depIdxs = []int32{
	0, // 0: tankgame.PlayerInput.input_type:type_name -> tankgame.InputType
	2, // 1: tankgame.FrameInputs.inputs:type_name -> tankgame.PlayerInput
	3, // 2: tankgame.ServerMessage.frame_inputs:type_name -> tankgame.FrameInputs
	4, // 3: tankgame.ServerMessage.room_info:type_name -> tankgame.RoomInfo
	5, // 4: tankgame.ServerMessage.game_start:type_name -> tankgame.GameStart
	1, // 5: tankgame.ServerMessage.connect_success:type_name -> tankgame.ConnectSuccess
	2, // 6: tankgame.ClientMessage.player_input:type_name -> tankgame.PlayerInput
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	file_proto_game_proto_msgTypes[5].OneofWrappers = []any{
		(*ServerMessage_FrameInputs)(nil),
		(*ServerMessage_RoomInfo)(nil),
		(*ServerMessage_GameStart)(nil),
		(*ServerMessage_ConnectSuccess)(nil),
	}
	file_proto_game_proto_msgTypes[6].OneofWrappers = []any{
		(*ClientMessage_PlayerInput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
		EnumInfos:         file_proto_game_proto_enumTypes,
		MessageInfos:      file_proto_game_proto_msgTypes,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
