syntax = "proto3";

package tankgame;

option go_package = "server/proto";


// 连接成功，分配给客户端的 player_id
message ConnectSuccess {
  string your_player_id = 1;
}

// 玩家信息
message PlayerInfo {
  string player_id = 1;
  string player_name = 2;
  int32 color_r = 3;
  int32 color_g = 4;
  int32 color_b = 5;
  int32 player_role = 6;
}

// 房间信息
message RoomInfo {
  string room_id = 1;
  repeated string player_ids = 2;
  string status = 3; // "waiting", "playing", "ended"
  string host_id = 4; // 房主ID
  int32 max_players = 5; // 最大玩家数
  string room_name = 6; // 房间名称
  repeated PlayerInfo player_infos = 7; // 玩家详细信息
  string host_name = 8; // 房主名字
}

// 房间列表
message RoomList {
  repeated RoomInfo rooms = 1;
}

// 创建房间请求
message CreateRoomRequest {
  string room_name = 1;
  int32 max_players = 2;
  string player_name = 3;  // 玩家名字
  int32 color_r = 4;       // 颜色R分量
  int32 color_g = 5;       // 颜色G分量
  int32 color_b = 6;       // 颜色B分量
  int32 player_role=7;     // 角色选择
}


// 加入房间请求
message JoinRoomRequest {
  string room_id = 1;
  string player_name = 2;  // 玩家名字
  int32 color_r = 3;       // 颜色R分量
  int32 color_g = 4;       // 颜色G分量
  int32 color_b = 5;       // 颜色B分量
  int32 player_role=6;     // 角色选择
}

// 离开房间请求
message LeaveRoomRequest {
  string room_id = 1;
}

// 踢人请求
message KickPlayerRequest {
  string room_id = 1;
  string target_player_id = 2; // 被踢的玩家ID
}

// 游戏结束请求
message GameOverRequest{
  string room_id=1;
}


// 玩家输入类型（8方向移动）
enum InputType {
  INPUT_NONE = 0;
  INPUT_MOVE_UP = 1;
  INPUT_MOVE_DOWN = 2;
  INPUT_MOVE_LEFT = 3;
  INPUT_MOVE_RIGHT = 4;
  INPUT_MOVE_UP_LEFT = 5;    // 左上
  INPUT_MOVE_UP_RIGHT = 6;   // 右上
  INPUT_MOVE_DOWN_LEFT = 7;  // 左下
  INPUT_MOVE_DOWN_RIGHT = 8; // 右下
}



// 游戏开始
message GameStart {
  string room_id = 1;
  repeated PlayerInfo player_infos = 2;
  int64 random_seed = 3; // 新增
  int32 level = 4; // 关卡索引
}

message RoomListRequest {}

message GameStartRequest{
  string room_id = 1;
  int32 level = 2; // 关卡索引
}

// 帧数据（客户端发送）
message FrameData {
  string player_id = 1;
  int64 time_stamp = 2;
  InputType input_type = 3;  // 移动输入，0表示无输入
  int64 shoot_x = 4;  // 开火位置X，0表示未开火
  int64 shoot_y = 5;  // 开火位置Y，0表示未开火
  int32 food_id = 6;  // 选择的食物ID，0表示未选择
}

// 服务器帧消息（服务器广播）
message ServerFrame {
  int64 time_stamp = 1;
  repeated FrameData frame_datas = 2;
}

// 服务器消息
message ServerMessage {
  oneof data {
    ServerFrame server_frame = 1;
    RoomInfo room_info = 2;
    GameStart game_start = 3;
    ConnectSuccess connect_success = 4;
    RoomList room_list = 5;
  }
}




// 客户端消息
message ClientMessage {
  oneof data {
    FrameData frame_data = 1;  // 帧数据（移动、开火、选择食物）
    CreateRoomRequest create_room_request = 2;
    JoinRoomRequest join_room_request = 3;
    LeaveRoomRequest leave_room_request = 4;
    RoomListRequest room_list_request = 5;
    GameStartRequest game_start_request = 6;
    KickPlayerRequest kick_player_request = 7;
    GameOverRequest game_over_request = 8;
  }
}