// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家输入类型
type InputType int32

const (
	InputType_INPUT_NONE       InputType = 0
	InputType_INPUT_MOVE_UP    InputType = 1
	InputType_INPUT_MOVE_DOWN  InputType = 2
	InputType_INPUT_MOVE_LEFT  InputType = 3
	InputType_INPUT_MOVE_RIGHT InputType = 4
	InputType_INPUT_SHOOT      InputType = 5
)

// Enum value maps for InputType.
var (
	InputType_name = map[int32]string{
		0: "INPUT_NONE",
		1: "INPUT_MOVE_UP",
		2: "INPUT_MOVE_DOWN",
		3: "INPUT_MOVE_LEFT",
		4: "INPUT_MOVE_RIGHT",
		5: "INPUT_SHOOT",
	}
	InputType_value = map[string]int32{
		"INPUT_NONE":       0,
		"INPUT_MOVE_UP":    1,
		"INPUT_MOVE_DOWN":  2,
		"INPUT_MOVE_LEFT":  3,
		"INPUT_MOVE_RIGHT": 4,
		"INPUT_SHOOT":      5,
	}
)

func (x InputType) Enum() *InputType {
	p := new(InputType)
	*p = x
	return p
}

func (x InputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InputType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_proto_enumTypes[0].Descriptor()
}

func (InputType) Type() protoreflect.EnumType {
	return &file_proto_game_proto_enumTypes[0]
}

func (x InputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InputType.Descriptor instead.
func (InputType) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

// 连接成功，分配给客户端的 player_id
type ConnectSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YourPlayerId  string                 `protobuf:"bytes,1,opt,name=your_player_id,json=yourPlayerId,proto3" json:"your_player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectSuccess) Reset() {
	*x = ConnectSuccess{}
	mi := &file_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectSuccess) ProtoMessage() {}

func (x *ConnectSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectSuccess.ProtoReflect.Descriptor instead.
func (*ConnectSuccess) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectSuccess) GetYourPlayerId() string {
	if x != nil {
		return x.YourPlayerId
	}
	return ""
}

// 玩家信息
type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	ColorR        int32                  `protobuf:"varint,3,opt,name=color_r,json=colorR,proto3" json:"color_r,omitempty"`
	ColorG        int32                  `protobuf:"varint,4,opt,name=color_g,json=colorG,proto3" json:"color_g,omitempty"`
	ColorB        int32                  `protobuf:"varint,5,opt,name=color_b,json=colorB,proto3" json:"color_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerInfo) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerInfo) GetColorR() int32 {
	if x != nil {
		return x.ColorR
	}
	return 0
}

func (x *PlayerInfo) GetColorG() int32 {
	if x != nil {
		return x.ColorG
	}
	return 0
}

func (x *PlayerInfo) GetColorB() int32 {
	if x != nil {
		return x.ColorB
	}
	return 0
}

// 房间信息
type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerIds     []string               `protobuf:"bytes,2,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                              // "waiting", "playing", "ended"
	HostId        string                 `protobuf:"bytes,4,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                // 房主ID
	MaxPlayers    int32                  `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`   // 最大玩家数
	RoomName      string                 `protobuf:"bytes,6,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`          // 房间名称
	PlayerInfos   []*PlayerInfo          `protobuf:"bytes,7,rep,name=player_infos,json=playerInfos,proto3" json:"player_infos,omitempty"` // 玩家详细信息
	HostName      string                 `protobuf:"bytes,8,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`          // 房主名字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *RoomInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RoomInfo) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RoomInfo) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *RoomInfo) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomInfo) GetPlayerInfos() []*PlayerInfo {
	if x != nil {
		return x.PlayerInfos
	}
	return nil
}

func (x *RoomInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

// 房间列表
type RoomList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomList) Reset() {
	*x = RoomList{}
	mi := &file_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomList) ProtoMessage() {}

func (x *RoomList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomList.ProtoReflect.Descriptor instead.
func (*RoomList) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *RoomList) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// 创建房间请求
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,2,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	PlayerName    string                 `protobuf:"bytes,3,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"` // 玩家名字
	ColorR        int32                  `protobuf:"varint,4,opt,name=color_r,json=colorR,proto3" json:"color_r,omitempty"`            // 颜色R分量
	ColorG        int32                  `protobuf:"varint,5,opt,name=color_g,json=colorG,proto3" json:"color_g,omitempty"`            // 颜色G分量
	ColorB        int32                  `protobuf:"varint,6,opt,name=color_b,json=colorB,proto3" json:"color_b,omitempty"`            // 颜色B分量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CreateRoomRequest) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *CreateRoomRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *CreateRoomRequest) GetColorR() int32 {
	if x != nil {
		return x.ColorR
	}
	return 0
}

func (x *CreateRoomRequest) GetColorG() int32 {
	if x != nil {
		return x.ColorG
	}
	return 0
}

func (x *CreateRoomRequest) GetColorB() int32 {
	if x != nil {
		return x.ColorB
	}
	return 0
}

// 加入房间请求
type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"` // 玩家名字
	ColorR        int32                  `protobuf:"varint,3,opt,name=color_r,json=colorR,proto3" json:"color_r,omitempty"`            // 颜色R分量
	ColorG        int32                  `protobuf:"varint,4,opt,name=color_g,json=colorG,proto3" json:"color_g,omitempty"`            // 颜色G分量
	ColorB        int32                  `protobuf:"varint,5,opt,name=color_b,json=colorB,proto3" json:"color_b,omitempty"`            // 颜色B分量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_proto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *JoinRoomRequest) GetColorR() int32 {
	if x != nil {
		return x.ColorR
	}
	return 0
}

func (x *JoinRoomRequest) GetColorG() int32 {
	if x != nil {
		return x.ColorG
	}
	return 0
}

func (x *JoinRoomRequest) GetColorB() int32 {
	if x != nil {
		return x.ColorB
	}
	return 0
}

// 离开房间请求
type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_proto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// 踢人请求
type KickPlayerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TargetPlayerId string                 `protobuf:"bytes,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"` // 被踢的玩家ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KickPlayerRequest) Reset() {
	*x = KickPlayerRequest{}
	mi := &file_proto_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerRequest) ProtoMessage() {}

func (x *KickPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerRequest.ProtoReflect.Descriptor instead.
func (*KickPlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{7}
}

func (x *KickPlayerRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *KickPlayerRequest) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

// 游戏结束请求
type GameOverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOverRequest) Reset() {
	*x = GameOverRequest{}
	mi := &file_proto_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOverRequest) ProtoMessage() {}

func (x *GameOverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOverRequest.ProtoReflect.Descriptor instead.
func (*GameOverRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{8}
}

func (x *GameOverRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// 玩家输入
type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	InputType     InputType              `protobuf:"varint,2,opt,name=input_type,json=inputType,proto3,enum=tankgame.InputType" json:"input_type,omitempty"`
	FrameNumber   int64                  `protobuf:"varint,3,opt,name=frame_number,json=frameNumber,proto3" json:"frame_number,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_proto_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerInput) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerInput) GetInputType() InputType {
	if x != nil {
		return x.InputType
	}
	return InputType_INPUT_NONE
}

func (x *PlayerInput) GetFrameNumber() int64 {
	if x != nil {
		return x.FrameNumber
	}
	return 0
}

func (x *PlayerInput) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 帧输入转发
type FrameInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameNumber   int64                  `protobuf:"varint,1,opt,name=frame_number,json=frameNumber,proto3" json:"frame_number,omitempty"`
	Inputs        []*PlayerInput         `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameInputs) Reset() {
	*x = FrameInputs{}
	mi := &file_proto_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameInputs) ProtoMessage() {}

func (x *FrameInputs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameInputs.ProtoReflect.Descriptor instead.
func (*FrameInputs) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{10}
}

func (x *FrameInputs) GetFrameNumber() int64 {
	if x != nil {
		return x.FrameNumber
	}
	return 0
}

func (x *FrameInputs) GetInputs() []*PlayerInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// 空帧同步（没有输入时发送）
type EmptyFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameNumber   int64                  `protobuf:"varint,1,opt,name=frame_number,json=frameNumber,proto3" json:"frame_number,omitempty"`
	ServerTime    float32                `protobuf:"fixed32,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyFrame) Reset() {
	*x = EmptyFrame{}
	mi := &file_proto_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyFrame) ProtoMessage() {}

func (x *EmptyFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyFrame.ProtoReflect.Descriptor instead.
func (*EmptyFrame) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{11}
}

func (x *EmptyFrame) GetFrameNumber() int64 {
	if x != nil {
		return x.FrameNumber
	}
	return 0
}

func (x *EmptyFrame) GetServerTime() float32 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// 游戏开始
type GameStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerInfos   []*PlayerInfo          `protobuf:"bytes,2,rep,name=player_infos,json=playerInfos,proto3" json:"player_infos,omitempty"`
	RandomSeed    int64                  `protobuf:"varint,3,opt,name=random_seed,json=randomSeed,proto3" json:"random_seed,omitempty"` // 新增
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                             // 关卡索引
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStart) Reset() {
	*x = GameStart{}
	mi := &file_proto_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStart) ProtoMessage() {}

func (x *GameStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStart.ProtoReflect.Descriptor instead.
func (*GameStart) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{12}
}

func (x *GameStart) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameStart) GetPlayerInfos() []*PlayerInfo {
	if x != nil {
		return x.PlayerInfos
	}
	return nil
}

func (x *GameStart) GetRandomSeed() int64 {
	if x != nil {
		return x.RandomSeed
	}
	return 0
}

func (x *GameStart) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type RoomListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListRequest) Reset() {
	*x = RoomListRequest{}
	mi := &file_proto_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListRequest) ProtoMessage() {}

func (x *RoomListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListRequest.ProtoReflect.Descriptor instead.
func (*RoomListRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{13}
}

type GameStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"` // 关卡索引
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStartRequest) Reset() {
	*x = GameStartRequest{}
	mi := &file_proto_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStartRequest) ProtoMessage() {}

func (x *GameStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStartRequest.ProtoReflect.Descriptor instead.
func (*GameStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{14}
}

func (x *GameStartRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameStartRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// 服务器消息
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ServerMessage_FrameInputs
	//	*ServerMessage_RoomInfo
	//	*ServerMessage_GameStart
	//	*ServerMessage_ConnectSuccess
	//	*ServerMessage_RoomList
	//	*ServerMessage_EmptyFrame
	Data          isServerMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{15}
}

func (x *ServerMessage) GetData() isServerMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ServerMessage) GetFrameInputs() *FrameInputs {
	if x != nil {
		if x, ok := x.Data.(*ServerMessage_FrameInputs); ok {
			return x.FrameInputs
		}
	}
	return nil
}

func (x *ServerMessage) GetRoomInfo() *RoomInfo {
	if x != nil {
		if x, ok := x.Data.(*ServerMessage_RoomInfo); ok {
			return x.RoomInfo
		}
	}
	return nil
}

func (x *ServerMessage) GetGameStart() *GameStart {
	if x != nil {
		if x, ok := x.Data.(*ServerMessage_GameStart); ok {
			return x.GameStart
		}
	}
	return nil
}

func (x *ServerMessage) GetConnectSuccess() *ConnectSuccess {
	if x != nil {
		if x, ok := x.Data.(*ServerMessage_ConnectSuccess); ok {
			return x.ConnectSuccess
		}
	}
	return nil
}

func (x *ServerMessage) GetRoomList() *RoomList {
	if x != nil {
		if x, ok := x.Data.(*ServerMessage_RoomList); ok {
			return x.RoomList
		}
	}
	return nil
}

func (x *ServerMessage) GetEmptyFrame() *EmptyFrame {
	if x != nil {
		if x, ok := x.Data.(*ServerMessage_EmptyFrame); ok {
			return x.EmptyFrame
		}
	}
	return nil
}

type isServerMessage_Data interface {
	isServerMessage_Data()
}

type ServerMessage_FrameInputs struct {
	FrameInputs *FrameInputs `protobuf:"bytes,1,opt,name=frame_inputs,json=frameInputs,proto3,oneof"`
}

type ServerMessage_RoomInfo struct {
	RoomInfo *RoomInfo `protobuf:"bytes,2,opt,name=room_info,json=roomInfo,proto3,oneof"`
}

type ServerMessage_GameStart struct {
	GameStart *GameStart `protobuf:"bytes,3,opt,name=game_start,json=gameStart,proto3,oneof"`
}

type ServerMessage_ConnectSuccess struct {
	ConnectSuccess *ConnectSuccess `protobuf:"bytes,4,opt,name=connect_success,json=connectSuccess,proto3,oneof"`
}

type ServerMessage_RoomList struct {
	RoomList *RoomList `protobuf:"bytes,5,opt,name=room_list,json=roomList,proto3,oneof"`
}

type ServerMessage_EmptyFrame struct {
	EmptyFrame *EmptyFrame `protobuf:"bytes,6,opt,name=empty_frame,json=emptyFrame,proto3,oneof"`
}

func (*ServerMessage_FrameInputs) isServerMessage_Data() {}

func (*ServerMessage_RoomInfo) isServerMessage_Data() {}

func (*ServerMessage_GameStart) isServerMessage_Data() {}

func (*ServerMessage_ConnectSuccess) isServerMessage_Data() {}

func (*ServerMessage_RoomList) isServerMessage_Data() {}

func (*ServerMessage_EmptyFrame) isServerMessage_Data() {}

// 客户端消息
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ClientMessage_PlayerInput
	//	*ClientMessage_CreateRoomRequest
	//	*ClientMessage_JoinRoomRequest
	//	*ClientMessage_LeaveRoomRequest
	//	*ClientMessage_RoomListRequest
	//	*ClientMessage_GameStartRequest
	//	*ClientMessage_KickPlayerRequest
	//	*ClientMessage_GameOverRequest
	Data          isClientMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_proto_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{16}
}

func (x *ClientMessage) GetData() isClientMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClientMessage) GetPlayerInput() *PlayerInput {
	if x != nil {
		if x, ok := x.Data.(*ClientMessage_PlayerInput); ok {
			return x.PlayerInput
		}
	}
	return nil
}

func (x *ClientMessage) GetCreateRoomRequest() *CreateRoomRequest {
	if x != nil {
		if x, ok := x.Data.(*ClientMessage_CreateRoomRequest); ok {
			return x.CreateRoomRequest
		}
	}
	return nil
}

func (x *ClientMessage) GetJoinRoomRequest() *JoinRoomRequest {
	if x != nil {
		if x, ok := x.Data.(*ClientMessage_JoinRoomRequest); ok {
			return x.JoinRoomRequest
		}
	}
	return nil
}

func (x *ClientMessage) GetLeaveRoomRequest() *LeaveRoomRequest {
	if x != nil {
		if x, ok := x.Data.(*ClientMessage_LeaveRoomRequest); ok {
			return x.LeaveRoomRequest
		}
	}
	return nil
}

func (x *ClientMessage) GetRoomListRequest() *RoomListRequest {
	if x != nil {
		if x, ok := x.Data.(*ClientMessage_RoomListRequest); ok {
			return x.RoomListRequest
		}
	}
	return nil
}

func (x *ClientMessage) GetGameStartRequest() *GameStartRequest {
	if x != nil {
		if x, ok := x.Data.(*ClientMessage_GameStartRequest); ok {
			return x.GameStartRequest
		}
	}
	return nil
}

func (x *ClientMessage) GetKickPlayerRequest() *KickPlayerRequest {
	if x != nil {
		if x, ok := x.Data.(*ClientMessage_KickPlayerRequest); ok {
			return x.KickPlayerRequest
		}
	}
	return nil
}

func (x *ClientMessage) GetGameOverRequest() *GameOverRequest {
	if x != nil {
		if x, ok := x.Data.(*ClientMessage_GameOverRequest); ok {
			return x.GameOverRequest
		}
	}
	return nil
}

type isClientMessage_Data interface {
	isClientMessage_Data()
}

type ClientMessage_PlayerInput struct {
	PlayerInput *PlayerInput `protobuf:"bytes,1,opt,name=player_input,json=playerInput,proto3,oneof"`
}

type ClientMessage_CreateRoomRequest struct {
	CreateRoomRequest *CreateRoomRequest `protobuf:"bytes,2,opt,name=create_room_request,json=createRoomRequest,proto3,oneof"`
}

type ClientMessage_JoinRoomRequest struct {
	JoinRoomRequest *JoinRoomRequest `protobuf:"bytes,3,opt,name=join_room_request,json=joinRoomRequest,proto3,oneof"`
}

type ClientMessage_LeaveRoomRequest struct {
	LeaveRoomRequest *LeaveRoomRequest `protobuf:"bytes,4,opt,name=leave_room_request,json=leaveRoomRequest,proto3,oneof"`
}

type ClientMessage_RoomListRequest struct {
	RoomListRequest *RoomListRequest `protobuf:"bytes,5,opt,name=room_list_request,json=roomListRequest,proto3,oneof"`
}

type ClientMessage_GameStartRequest struct {
	GameStartRequest *GameStartRequest `protobuf:"bytes,6,opt,name=game_start_request,json=gameStartRequest,proto3,oneof"`
}

type ClientMessage_KickPlayerRequest struct {
	KickPlayerRequest *KickPlayerRequest `protobuf:"bytes,7,opt,name=kick_player_request,json=kickPlayerRequest,proto3,oneof"`
}

type ClientMessage_GameOverRequest struct {
	GameOverRequest *GameOverRequest `protobuf:"bytes,8,opt,name=game_over_request,json=gameOverRequest,proto3,oneof"`
}

func (*ClientMessage_PlayerInput) isClientMessage_Data() {}

func (*ClientMessage_CreateRoomRequest) isClientMessage_Data() {}

func (*ClientMessage_JoinRoomRequest) isClientMessage_Data() {}

func (*ClientMessage_LeaveRoomRequest) isClientMessage_Data() {}

func (*ClientMessage_RoomListRequest) isClientMessage_Data() {}

func (*ClientMessage_GameStartRequest) isClientMessage_Data() {}

func (*ClientMessage_KickPlayerRequest) isClientMessage_Data() {}

func (*ClientMessage_GameOverRequest) isClientMessage_Data() {}

var File_proto_game_proto protoreflect.FileDescriptor

const file_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x10proto/game.proto\x12\btankgame\"6\n" +
	"\x0eConnectSuccess\x12$\n" +
	"\x0eyour_player_id\x18\x01 \x01(\tR\fyourPlayerId\"\x95\x01\n" +
	"\n" +
	"PlayerInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x17\n" +
	"\acolor_r\x18\x03 \x01(\x05R\x06colorR\x12\x17\n" +
	"\acolor_g\x18\x04 \x01(\x05R\x06colorG\x12\x17\n" +
	"\acolor_b\x18\x05 \x01(\x05R\x06colorB\"\x87\x02\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\tR\tplayerIds\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x17\n" +
	"\ahost_id\x18\x04 \x01(\tR\x06hostId\x12\x1f\n" +
	"\vmax_players\x18\x05 \x01(\x05R\n" +
	"maxPlayers\x12\x1b\n" +
	"\troom_name\x18\x06 \x01(\tR\broomName\x127\n" +
	"\fplayer_infos\x18\a \x03(\v2\x14.tankgame.PlayerInfoR\vplayerInfos\x12\x1b\n" +
	"\thost_name\x18\b \x01(\tR\bhostName\"4\n" +
	"\bRoomList\x12(\n" +
	"\x05rooms\x18\x01 \x03(\v2\x12.tankgame.RoomInfoR\x05rooms\"\xbd\x01\n" +
	"\x11CreateRoomRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1f\n" +
	"\vmax_players\x18\x02 \x01(\x05R\n" +
	"maxPlayers\x12\x1f\n" +
	"\vplayer_name\x18\x03 \x01(\tR\n" +
	"playerName\x12\x17\n" +
	"\acolor_r\x18\x04 \x01(\x05R\x06colorR\x12\x17\n" +
	"\acolor_g\x18\x05 \x01(\x05R\x06colorG\x12\x17\n" +
	"\acolor_b\x18\x06 \x01(\x05R\x06colorB\"\x96\x01\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x17\n" +
	"\acolor_r\x18\x03 \x01(\x05R\x06colorR\x12\x17\n" +
	"\acolor_g\x18\x04 \x01(\x05R\x06colorG\x12\x17\n" +
	"\acolor_b\x18\x05 \x01(\x05R\x06colorB\"+\n" +
	"\x10LeaveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"V\n" +
	"\x11KickPlayerRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\tR\x0etargetPlayerId\"*\n" +
	"\x0fGameOverRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x9f\x01\n" +
	"\vPlayerInput\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x122\n" +
	"\n" +
	"input_type\x18\x02 \x01(\x0e2\x13.tankgame.InputTypeR\tinputType\x12!\n" +
	"\fframe_number\x18\x03 \x01(\x03R\vframeNumber\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"_\n" +
	"\vFrameInputs\x12!\n" +
	"\fframe_number\x18\x01 \x01(\x03R\vframeNumber\x12-\n" +
	"\x06inputs\x18\x02 \x03(\v2\x15.tankgame.PlayerInputR\x06inputs\"P\n" +
	"\n" +
	"EmptyFrame\x12!\n" +
	"\fframe_number\x18\x01 \x01(\x03R\vframeNumber\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x02R\n" +
	"serverTime\"\x94\x01\n" +
	"\tGameStart\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x127\n" +
	"\fplayer_infos\x18\x02 \x03(\v2\x14.tankgame.PlayerInfoR\vplayerInfos\x12\x1f\n" +
	"\vrandom_seed\x18\x03 \x01(\x03R\n" +
	"randomSeed\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\"\x11\n" +
	"\x0fRoomListRequest\"A\n" +
	"\x10GameStartRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"\xed\x02\n" +
	"\rServerMessage\x12:\n" +
	"\fframe_inputs\x18\x01 \x01(\v2\x15.tankgame.FrameInputsH\x00R\vframeInputs\x121\n" +
	"\troom_info\x18\x02 \x01(\v2\x12.tankgame.RoomInfoH\x00R\broomInfo\x124\n" +
	"\n" +
	"game_start\x18\x03 \x01(\v2\x13.tankgame.GameStartH\x00R\tgameStart\x12C\n" +
	"\x0fconnect_success\x18\x04 \x01(\v2\x18.tankgame.ConnectSuccessH\x00R\x0econnectSuccess\x121\n" +
	"\troom_list\x18\x05 \x01(\v2\x12.tankgame.RoomListH\x00R\broomList\x127\n" +
	"\vempty_frame\x18\x06 \x01(\v2\x14.tankgame.EmptyFrameH\x00R\n" +
	"emptyFrameB\x06\n" +
	"\x04data\"\xe4\x04\n" +
	"\rClientMessage\x12:\n" +
	"\fplayer_input\x18\x01 \x01(\v2\x15.tankgame.PlayerInputH\x00R\vplayerInput\x12M\n" +
	"\x13create_room_request\x18\x02 \x01(\v2\x1b.tankgame.CreateRoomRequestH\x00R\x11createRoomRequest\x12G\n" +
	"\x11join_room_request\x18\x03 \x01(\v2\x19.tankgame.JoinRoomRequestH\x00R\x0fjoinRoomRequest\x12J\n" +
	"\x12leave_room_request\x18\x04 \x01(\v2\x1a.tankgame.LeaveRoomRequestH\x00R\x10leaveRoomRequest\x12G\n" +
	"\x11room_list_request\x18\x05 \x01(\v2\x19.tankgame.RoomListRequestH\x00R\x0froomListRequest\x12J\n" +
	"\x12game_start_request\x18\x06 \x01(\v2\x1a.tankgame.GameStartRequestH\x00R\x10gameStartRequest\x12M\n" +
	"\x13kick_player_request\x18\a \x01(\v2\x1b.tankgame.KickPlayerRequestH\x00R\x11kickPlayerRequest\x12G\n" +
	"\x11game_over_request\x18\b \x01(\v2\x19.tankgame.GameOverRequestH\x00R\x0fgameOverRequestB\x06\n" +
	"\x04data*\x7f\n" +
	"\tInputType\x12\x0e\n" +
	"\n" +
	"INPUT_NONE\x10\x00\x12\x11\n" +
	"\rINPUT_MOVE_UP\x10\x01\x12\x13\n" +
	"\x0fINPUT_MOVE_DOWN\x10\x02\x12\x13\n" +
	"\x0fINPUT_MOVE_LEFT\x10\x03\x12\x14\n" +
	"\x10INPUT_MOVE_RIGHT\x10\x04\x12\x0f\n" +
	"\vINPUT_SHOOT\x10\x05B\x0eZ\fserver/protob\x06proto3"

var (
	file_proto_game_proto_rawDescOnce sync.Once
	file_proto_game_proto_rawDescData []byte
)

func file_proto_game_proto_rawDescGZIP() []byte {
	file_proto_game_proto_rawDescOnce.Do(func() {
		file_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)))
	})
	return file_proto_game_proto_rawDescData
}

var file_proto_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_game_proto_goTypes = []any{
	(InputType)(0),            // 0: tankgame.InputType
	(*ConnectSuccess)(nil),    // 1: tankgame.ConnectSuccess
	(*PlayerInfo)(nil),        // 2: tankgame.PlayerInfo
	(*RoomInfo)(nil),          // 3: tankgame.RoomInfo
	(*RoomList)(nil),          // 4: tankgame.RoomList
	(*CreateRoomRequest)(nil), // 5: tankgame.CreateRoomRequest
	(*JoinRoomRequest)(nil),   // 6: tankgame.JoinRoomRequest
	(*LeaveRoomRequest)(nil),  // 7: tankgame.LeaveRoomRequest
	(*KickPlayerRequest)(nil), // 8: tankgame.KickPlayerRequest
	(*GameOverRequest)(nil),   // 9: tankgame.GameOverRequest
	(*PlayerInput)(nil),       // 10: tankgame.PlayerInput
	(*FrameInputs)(nil),       // 11: tankgame.FrameInputs
	(*EmptyFrame)(nil),        // 12: tankgame.EmptyFrame
	(*GameStart)(nil),         // 13: tankgame.GameStart
	(*RoomListRequest)(nil),   // 14: tankgame.RoomListRequest
	(*GameStartRequest)(nil),  // 15: tankgame.GameStartRequest
	(*ServerMessage)(nil),     // 16: tankgame.ServerMessage
	(*ClientMessage)(nil),     // 17: tankgame.ClientMessage
}
var file_proto_game_proto_depIdxs = []int32{
	2,  // 0: tankgame.RoomInfo.player_infos:type_name -> tankgame.PlayerInfo
	3,  // 1: tankgame.RoomList.rooms:type_name -> tankgame.RoomInfo
	0,  // 2: tankgame.PlayerInput.input_type:type_name -> tankgame.InputType
	10, // 3: tankgame.FrameInputs.inputs:type_name -> tankgame.PlayerInput
	2,  // 4: tankgame.GameStart.player_infos:type_name -> tankgame.PlayerInfo
	11, // 5: tankgame.ServerMessage.frame_inputs:type_name -> tankgame.FrameInputs
	3,  // 6: tankgame.ServerMessage.room_info:type_name -> tankgame.RoomInfo
	13, // 7: tankgame.ServerMessage.game_start:type_name -> tankgame.GameStart
	1,  // 8: tankgame.ServerMessage.connect_success:type_name -> tankgame.ConnectSuccess
	4,  // 9: tankgame.ServerMessage.room_list:type_name -> tankgame.RoomList
	12, // 10: tankgame.ServerMessage.empty_frame:type_name -> tankgame.EmptyFrame
	10, // 11: tankgame.ClientMessage.player_input:type_name -> tankgame.PlayerInput
	5,  // 12: tankgame.ClientMessage.create_room_request:type_name -> tankgame.CreateRoomRequest
	6,  // 13: tankgame.ClientMessage.join_room_request:type_name -> tankgame.JoinRoomRequest
	7,  // 14: tankgame.ClientMessage.leave_room_request:type_name -> tankgame.LeaveRoomRequest
	14, // 15: tankgame.ClientMessage.room_list_request:type_name -> tankgame.RoomListRequest
	15, // 16: tankgame.ClientMessage.game_start_request:type_name -> tankgame.GameStartRequest
	8,  // 17: tankgame.ClientMessage.kick_player_request:type_name -> tankgame.KickPlayerRequest
	9,  // 18: tankgame.ClientMessage.game_over_request:type_name -> tankgame.GameOverRequest
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	file_proto_game_proto_msgTypes[15].OneofWrappers = []any{
		(*ServerMessage_FrameInputs)(nil),
		(*ServerMessage_RoomInfo)(nil),
		(*ServerMessage_GameStart)(nil),
		(*ServerMessage_ConnectSuccess)(nil),
		(*ServerMessage_RoomList)(nil),
		(*ServerMessage_EmptyFrame)(nil),
	}
	file_proto_game_proto_msgTypes[16].OneofWrappers = []any{
		(*ClientMessage_PlayerInput)(nil),
		(*ClientMessage_CreateRoomRequest)(nil),
		(*ClientMessage_JoinRoomRequest)(nil),
		(*ClientMessage_LeaveRoomRequest)(nil),
		(*ClientMessage_RoomListRequest)(nil),
		(*ClientMessage_GameStartRequest)(nil),
		(*ClientMessage_KickPlayerRequest)(nil),
		(*ClientMessage_GameOverRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
		EnumInfos:         file_proto_game_proto_enumTypes,
		MessageInfos:      file_proto_game_proto_msgTypes,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
